# config/packages/cache.yaml

framework:
    cache:
        # Your main "app" cache can go here (default filesystem). If you use Redis:
        # app: cache.adapter.redis
        # default_redis_provider: redis://localhost

        # Define any named pools below
        pools:
            rate_limiter_storage:
                adapter: cache.app
            # my.dedicated.cache: null
