# config/packages/rate_limiter.yaml
framework:
    rate_limiter:
        chat_api:
            policy:   'token_bucket'
            limit:    3
            rate:
                interval: '5 seconds'
                amount:   3
