controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

chat_api:
    path: /api/chat
    controller: App\Controller\ChatController::chat
    methods: [POST]
