# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    ticketmaster.api_key: '%env(TICKETMASTER_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $apiKey: '%ticketmaster.api_key%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JwtService:
        arguments:
            $jwtSecret: '%env(JWT_SECRET)%' # Should match the construct in JwtService
    App\EventListener\JwtRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 5 }
    App\EventSubscriber\JwtUserSubscriber:
        tags:
            - { name: kernel.event_subscriber }

twig:
    globals:
        recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
